package reallyfastmode.protocol.VanillaCatalog;

import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.Map;

/** Generated by VanillaPotionCatalogGenerator. Do not edit by hand. */
public enum VanillaPotionCatalog {
    AMBROSIA(0, "Ambrosia"),
    ANCIENT_POTION(1, "Ancient Potion"),
    ATTACKPOTION(2, "AttackPotion"),
    BLESSINGOFTHEFORGE(3, "BlessingOfTheForge"),
    BLOCK_POTION(4, "Block Potion"),
    BLOODPOTION(5, "BloodPotion"),
    BOTTLEDMIRACLE(6, "BottledMiracle"),
    COLORLESSPOTION(7, "ColorlessPotion"),
    CULTISTPOTION(8, "CultistPotion"),
    CUNNINGPOTION(9, "CunningPotion"),
    DEXTERITY_POTION(10, "Dexterity Potion"),
    DISTILLEDCHAOS(11, "DistilledChaos"),
    DUPLICATIONPOTION(12, "DuplicationPotion"),
    ELIXIRPOTION(13, "ElixirPotion"),
    ENERGY_POTION(14, "Energy Potion"),
    ENTROPICBREW(15, "EntropicBrew"),
    ESSENCEOFDARKNESS(16, "EssenceOfDarkness"),
    ESSENCEOFSTEEL(17, "EssenceOfSteel"),
    EXPLOSIVE_POTION(18, "Explosive Potion"),
    FAIRYPOTION(19, "FairyPotion"),
    FEARPOTION(20, "FearPotion"),
    FIRE_POTION(21, "Fire Potion"),
    FOCUSPOTION(22, "FocusPotion"),
    FRUIT_JUICE(23, "Fruit Juice"),
    GAMBLERSBREW(24, "GamblersBrew"),
    GHOSTINAJAR(25, "GhostInAJar"),
    HEARTOFIRON(26, "HeartOfIron"),
    LIQUIDBRONZE(27, "LiquidBronze"),
    LIQUIDMEMORIES(28, "LiquidMemories"),
    POISON_POTION(29, "Poison Potion"),
    POTION_SLOT(30, "Potion Slot"),
    POTIONOFCAPACITY(31, "PotionOfCapacity"),
    POWERPOTION(32, "PowerPotion"),
    REGEN_POTION(33, "Regen Potion"),
    SKILLPOTION(34, "SkillPotion"),
    SMOKEBOMB(35, "SmokeBomb"),
    SNECKOOIL(36, "SneckoOil"),
    SPEEDPOTION(37, "SpeedPotion"),
    STANCEPOTION(38, "StancePotion"),
    STEROIDPOTION(39, "SteroidPotion"),
    STRENGTH_POTION(40, "Strength Potion"),
    SWIFT_POTION(41, "Swift Potion"),
    WEAK_POTION(42, "Weak Potion"),
    EMPTY(43, "Empty"),
    UNKNOWN(44, "Unknown");

    public static final Map<String, Integer> potionIdToWireId;

    static {
        Map<String, Integer> ids = new LinkedHashMap<String, Integer>();
        for (VanillaPotionCatalog value : values()) {
            ids.put(value.potionId, value.wireId);
        }
        potionIdToWireId = Collections.unmodifiableMap(ids);
    }

    public final int wireId;
    public final String potionId;

    VanillaPotionCatalog(int wireId, String potionId) {
        this.wireId = wireId;
        this.potionId = potionId;
    }
}
