package reallyfastmode.protocol;

import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.Map;

/** Generated by VanillaEventCatalogGenerator. Do not edit by hand. */
public enum VanillaEventCatalog {
    ACCURSED_BLACKSMITH(0, "Accursed Blacksmith"),
    ADDICT(1, "Addict"),
    BACK_TO_BASICS(2, "Back to Basics"),
    BEGGAR(3, "Beggar"),
    BIG_FISH(4, "Big Fish"),
    BONFIRE_ELEMENTALS(5, "Bonfire Elementals"),
    COLOSSEUM(6, "Colosseum"),
    CURSED_TOME(7, "Cursed Tome"),
    DEAD_ADVENTURER(8, "Dead Adventurer"),
    DESIGNER(9, "Designer"),
    DRUG_DEALER(10, "Drug Dealer"),
    DUPLICATOR(11, "Duplicator"),
    FACETRADER(12, "FaceTrader"),
    FALLING(13, "Falling"),
    FORGOTTEN_ALTAR(14, "Forgotten Altar"),
    FOUNTAIN_OF_CLEANSING(15, "Fountain of Cleansing"),
    GHOSTS(16, "Ghosts"),
    GOLDEN_IDOL(17, "Golden Idol"),
    GOLDEN_SHRINE(18, "Golden Shrine"),
    GOLDEN_WING(19, "Golden Wing"),
    KNOWING_SKULL(20, "Knowing Skull"),
    LAB(21, "Lab"),
    LIARS_GAME(22, "Liars Game"),
    LIVING_WALL(23, "Living Wall"),
    MASKED_BANDITS(24, "Masked Bandits"),
    MATCH_AND_KEEP(25, "Match and Keep!"),
    MINDBLOOM(26, "MindBloom"),
    MUSHROOMS(27, "Mushrooms"),
    MYSTERIOUS_SPHERE(28, "Mysterious Sphere"),
    N_LOTH(29, "N'loth"),
    NEST(30, "Nest"),
    NOTEFORYOURSELF(31, "NoteForYourself"),
    PURIFIER(32, "Purifier"),
    SCRAP_OOZE(33, "Scrap Ooze"),
    SECRETPORTAL(34, "SecretPortal"),
    SENSORYSTONE(35, "SensoryStone"),
    SHINING_LIGHT(36, "Shining Light"),
    SPIRE_HEART(37, "Spire Heart"),
    THE_CLERIC(38, "The Cleric"),
    THE_JOUST(39, "The Joust"),
    THE_LIBRARY(40, "The Library"),
    THE_MAUSOLEUM(41, "The Mausoleum"),
    THE_MOAI_HEAD(42, "The Moai Head"),
    THE_WOMAN_IN_BLUE(43, "The Woman in Blue"),
    TOMB_OF_LORD_RED_MASK(44, "Tomb of Lord Red Mask"),
    TRANSMORGRIFIER(45, "Transmorgrifier"),
    UPGRADE_SHRINE(46, "Upgrade Shrine"),
    VAMPIRES(47, "Vampires"),
    WEMEETAGAIN(48, "WeMeetAgain"),
    WHEEL_OF_CHANGE(49, "Wheel of Change"),
    WINDING_HALLS(50, "Winding Halls"),
    WORLD_OF_GOOP(51, "World of Goop");

    public static final Map<String, Integer> eventIdToWireId;

    static {
        Map<String, Integer> ids = new LinkedHashMap<String, Integer>();
        for (VanillaEventCatalog value : values()) {
            ids.put(value.eventId, value.wireId);
        }
        eventIdToWireId = Collections.unmodifiableMap(ids);
    }

    public final int wireId;
    public final String eventId;

    VanillaEventCatalog(int wireId, String eventId) {
        this.wireId = wireId;
        this.eventId = eventId;
    }
}
