package reallyfastmode.protocol;

import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.Map;

/** Generated by VanillaMonsterCatalogGenerator. Do not edit by hand. */
public enum VanillaMonsterCatalog {
    ACIDSLIME_L(0, "AcidSlime_L"),
    ACIDSLIME_M(1, "AcidSlime_M"),
    ACIDSLIME_S(2, "AcidSlime_S"),
    APOLOGY_SLIME(3, "Apology Slime"),
    AWAKENEDONE(4, "AwakenedOne"),
    BANDITBEAR(5, "BanditBear"),
    BANDITCHILD(6, "BanditChild"),
    BANDITLEADER(7, "BanditLeader"),
    BOOKOFSTABBING(8, "BookOfStabbing"),
    BRONZEAUTOMATON(9, "BronzeAutomaton"),
    BRONZEORB(10, "BronzeOrb"),
    BYRD(11, "Byrd"),
    CENTURION(12, "Centurion"),
    CHAMP(13, "Champ"),
    CHOSEN(14, "Chosen"),
    CORRUPTHEART(15, "CorruptHeart"),
    CULTIST(16, "Cultist"),
    DAGGER(17, "Dagger"),
    DARKLING(18, "Darkling"),
    DECA(19, "Deca"),
    DONU(20, "Donu"),
    EXPLODER(21, "Exploder"),
    FUNGIBEAST(22, "FungiBeast"),
    FUZZYLOUSEDEFENSIVE(23, "FuzzyLouseDefensive"),
    FUZZYLOUSENORMAL(24, "FuzzyLouseNormal"),
    GIANTHEAD(25, "GiantHead"),
    GREMLINFAT(26, "GremlinFat"),
    GREMLINLEADER(27, "GremlinLeader"),
    GREMLINNOB(28, "GremlinNob"),
    GREMLINTHIEF(29, "GremlinThief"),
    GREMLINTSUNDERE(30, "GremlinTsundere"),
    GREMLINWARRIOR(31, "GremlinWarrior"),
    GREMLINWIZARD(32, "GremlinWizard"),
    HEALER(33, "Healer"),
    HEXAGHOST(34, "Hexaghost"),
    JAWWORM(35, "JawWorm"),
    LAGAVULIN(36, "Lagavulin"),
    LOOTER(37, "Looter"),
    MAW(38, "Maw"),
    MUGGER(39, "Mugger"),
    NEMESIS(40, "Nemesis"),
    ORB_WALKER(41, "Orb Walker"),
    REPTOMANCER(42, "Reptomancer"),
    REPULSOR(43, "Repulsor"),
    SENTRY(44, "Sentry"),
    SERPENT(45, "Serpent"),
    SHELLED_PARASITE(46, "Shelled Parasite"),
    SLAVERBLUE(47, "SlaverBlue"),
    SLAVERBOSS(48, "SlaverBoss"),
    SLAVERRED(49, "SlaverRed"),
    SLIMEBOSS(50, "SlimeBoss"),
    SNAKEPLANT(51, "SnakePlant"),
    SNECKO(52, "Snecko"),
    SPHERICGUARDIAN(53, "SphericGuardian"),
    SPIKESLIME_L(54, "SpikeSlime_L"),
    SPIKESLIME_M(55, "SpikeSlime_M"),
    SPIKESLIME_S(56, "SpikeSlime_S"),
    SPIKER(57, "Spiker"),
    SPIRESHIELD(58, "SpireShield"),
    SPIRESPEAR(59, "SpireSpear"),
    THECOLLECTOR(60, "TheCollector"),
    THEGUARDIAN(61, "TheGuardian"),
    TIMEEATER(62, "TimeEater"),
    TORCHHEAD(63, "TorchHead"),
    TRANSIENT(64, "Transient"),
    WRITHINGMASS(65, "WrithingMass");

    public static final Map<String, Integer> monsterIdToWireId;

    static {
        Map<String, Integer> ids = new LinkedHashMap<String, Integer>();
        for (VanillaMonsterCatalog value : values()) {
            ids.put(value.monsterId, value.wireId);
        }
        monsterIdToWireId = Collections.unmodifiableMap(ids);
    }

    public final int wireId;
    public final String monsterId;

    VanillaMonsterCatalog(int wireId, String monsterId) {
        this.wireId = wireId;
        this.monsterId = monsterId;
    }
}
